services:
  steel:
    image: ghcr.io/junkydeveloper/steelmc:nightly
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 25565:25565
    volumes:
      - ./config:/config
      - ./saves:/saves
