{
  description = "SteelMC development environment and server package";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (nixpkgs) lib;

      # x86_64-darwin is intentionally absent: nixpkgs dropped it in 26.11, and
      # evaluating it against nixos-unstable throws.
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "aarch64-darwin"
      ];

      # Only the Linux targets are built in CI. Darwin gets a devShell, but the
      # package is not claimed to work there until someone verifies it.
      linuxSystems = lib.filter (lib.hasSuffix "-linux") systems;

      forAllSystems =
        f:
        lib.genAttrs systems (
          system:
          f (
            import nixpkgs {
              inherit system;
              overlays = [ (import rust-overlay) ];
            }
          )
        );

      # Generated by ./update-minecraft-assets.sh from [workspace.package].version
      # in Cargo.toml, which is the single source of truth for the targeted
      # Minecraft version. CI fails if this file is stale.
      assets = builtins.fromJSON (builtins.readFile ./nix/minecraft-assets.json);

      perSystem = forAllSystems (
        pkgs:
        let
          toolchain = pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;

          rustPlatform = pkgs.makeRustPlatform {
            cargo = toolchain;
            rustc = toolchain;
          };

          # steel-utils/build/build.rs downloads this jar at build time. Nix builds
          # have no network, so it is fetched as a fixed-output derivation instead.
          #
          # Note: fixed-output derivations are pushed to binary caches. If this
          # project ever publishes one, that would mean redistributing Mojang's
          # server jar from project infrastructure. Exclude this path if so.
          serverJar = pkgs.fetchurl { inherit (assets.serverJar) url hash; };

          # Reproduces the layout that `download_and_extract_assets` writes into
          # steel-utils/build_assets. Consumed by steel-utils' own build script and
          # by steel-registry/build/, which reads
          # ../steel-utils/build_assets/builtin_datapacks/minecraft/** for damage
          # types, timelines, tags, carvers and more.
          buildAssets =
            pkgs.runCommand "steel-build-assets-${assets.minecraftVersion}"
              {
                nativeBuildInputs = [
                  pkgs.unzip
                  pkgs.jq
                ];
              }
              ''
                unzip -qq ${serverJar} -d outer

                # The pinned jar and the targeted version are separate fields, so a
                # version bump that forgets to regenerate the pin would otherwise
                # produce a binary labelled with one version but carrying another
                # version's registries. Fail loudly instead.
                jarVersion=$(jq -r '.id' outer/version.json)
                if [ "$jarVersion" != "${assets.minecraftVersion}" ]; then
                  echo "error: pinned server jar is Minecraft $jarVersion, but the" >&2
                  echo "targeted version is ${assets.minecraftVersion}." >&2
                  echo "Run ./update-minecraft-assets.sh to regenerate the pin." >&2
                  exit 1
                fi

                # Modern server jars are bootstrap jars wrapping the real one.
                nested=$(find outer/META-INF/versions -name '*.jar' -print -quit 2>/dev/null || true)
                if [ -n "$nested" ]; then
                  unzip -qq "$nested" -d inner
                else
                  mv outer inner
                fi

                mkdir -p "$out/builtin_datapacks"
                cp -r inner/data/minecraft "$out/builtin_datapacks/minecraft"
                cp inner/assets/minecraft/lang/en_us.json "$out/en_us.json"

                chmod -R u+w "$out"
                printf '%s' "${assets.minecraftVersion}" > "$out/builtin_datapacks/minecraft/.version"
              '';

          steel = rustPlatform.buildRustPackage {
            pname = "steel";
            inherit (assets) version;

            src = ./.;

            cargoLock = {
              lockFile = ./Cargo.lock;
              outputHashes = {
                "text_components-0.1.7" = "sha256-cGVxp7QX9qYuPl/NW+ya889cCmj5D/bV7tW5SjzBohs=";
              };
            };

            # .cargo/config.toml links the Linux targets with -fuse-ld=lld.
            nativeBuildInputs = [ pkgs.lld ];

            # Staged here so the build script's assets_are_valid check short-circuits
            # before it reaches any network call.
            preBuild = ''
              mkdir -p steel-utils/build_assets
              cp -r --no-preserve=mode,ownership ${buildAssets}/. steel-utils/build_assets/
            '';

            cargoBuildFlags = [
              "--package"
              "steel"
            ];

            # Not run here: `cargo test` builds the full workspace a second time,
            # which roughly doubles an already long build. Tests run in CI instead.
            doCheck = false;

            meta = {
              description = "Minecraft server implementation written in Rust";
              homepage = "https://steelmc.dev";
              license = lib.licenses.agpl3Plus;
              mainProgram = "steel";
              platforms = linuxSystems;
            };
          };
        in
        {
          inherit pkgs toolchain steel;
        }
      );
    in
    {
      devShells = lib.mapAttrs (_: system: {
        default = system.pkgs.mkShell {
          packages = [
            system.toolchain

            system.pkgs.lld

            system.pkgs.prek
            system.pkgs.typos

            system.pkgs.git
            system.pkgs.jdk25
          ];
        };
      }) perSystem;

      packages = lib.mapAttrs (_: system: { default = system.steel; }) perSystem;

      # `nix flake check` builds the server on the platforms that claim support.
      checks = lib.genAttrs linuxSystems (system: { package = perSystem.${system}.steel; });

      formatter = lib.mapAttrs (_: system: system.pkgs.nixfmt-rfc-style) perSystem;
    };
}
