services:
  steel:
    image: steel
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: normal
    ports:
      - 25565:25565
    volumes:
      - ../config:/config
      - ../saves:/saves
