//! Filling a container from a loot table.
//!
//! Mirrors Vanilla `LootTable.fill`: roll the table, spread the results over the
//! container's empty slots, and split stacks so a sparse roll still looks
//! scattered rather than clumped at the front.

use simdnbt::borrow::NbtCompound as NbtCompoundView;
use simdnbt::owned::NbtCompound;
use std::mem;
use steel_registry::item_stack::ItemStack;
use steel_registry::loot_table::{LootContext, LootTableRef};
use steel_registry::{REGISTRY, RegistryExt as _};

use steel_utils::random::legacy_random::LegacyRandom;
use steel_utils::random::{Random, next_int_between, shuffle};
use steel_utils::{BlockPos, Identifier};

use crate::inventory::container::Container;

/// Vanilla `LootTable.fill`.
///
/// `context` must already carry the random source Vanilla selects for this fill:
/// a `LegacyRandom` seeded from the container's stored loot seed when that seed
/// is non-zero, otherwise the level's random source.
pub fn fill_container<R: Random>(
    table: LootTableRef,
    container: &mut dyn Container,
    context: &mut LootContext<'_, R>,
) {
    let mut items = table.get_random_items(context);
    let mut available_slots = available_slots(container, context.rng);
    shuffle_and_split_items(&mut items, available_slots.len(), context.rng);

    for item in items {
        let Some(slot) = available_slots.pop() else {
            log::warn!(
                "Tried to over-fill a container from loot table {}",
                table.key
            );
            return;
        };
        // Vanilla writes empty stacks too, clearing the slot it picked.
        container.set_item(slot, item);
    }
}

/// Vanilla `LootTable.getAvailableSlots`: every empty slot, shuffled.
fn available_slots<R: Random>(container: &dyn Container, random: &mut R) -> Vec<usize> {
    let mut slots: Vec<usize> = (0..container.get_container_size())
        .filter(|slot| container.get_item(*slot).is_empty())
        .collect();
    shuffle(&mut slots, random);
    slots
}

/// Vanilla `LootTable.shuffleAndSplitItems`.
///
/// Splits oversized stacks until the results roughly fill the available slots,
/// then shuffles the whole set.
fn shuffle_and_split_items<R: Random>(
    result: &mut Vec<ItemStack>,
    available_slots: usize,
    random: &mut R,
) {
    let mut splittable: Vec<ItemStack> = Vec::new();
    result.retain_mut(|item| {
        if item.is_empty() {
            return false;
        }
        if item.count() > 1 {
            splittable.push(mem::take(item));
            return false;
        }
        true
    });

    while !splittable.is_empty() && result.len() + splittable.len() < available_slots {
        let last = i32::try_from(splittable.len()).unwrap_or(i32::MAX) - 1;
        let index = next_int_between(random, 0, last) as usize;
        let mut item = splittable.remove(index);
        let remove = next_int_between(random, 1, item.count() / 2);
        let copy = item.split(remove);

        for part in [item, copy] {
            if part.count() > 1 && random.next_bool() {
                splittable.push(part);
            } else {
                result.push(part);
            }
        }
    }

    result.append(&mut splittable);
    shuffle(result, random);
}

/// Vanilla `RandomizableContainer`'s pending loot table.
///
/// A container generated by worldgen stores a loot table instead of items; the
/// table is rolled on first access and then cleared.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct ContainerLoot {
    loot_table: Option<Identifier>,
    seed: i64,
}

impl ContainerLoot {
    /// Vanilla `RandomizableContainer.tryLoadLootTable`.
    pub fn load(&mut self, nbt: &NbtCompoundView<'_, '_>) {
        self.loot_table = nbt
            .string("LootTable")
            .and_then(|value| value.to_string().parse().ok());
        self.seed = nbt.long("LootTableSeed").unwrap_or(0);
    }

    /// Vanilla `RandomizableContainer.trySaveLootTable`.
    ///
    /// Returns whether a table is still pending, which Vanilla uses to skip
    /// writing the item list.
    pub fn save(&self, nbt: &mut NbtCompound) -> bool {
        let Some(loot_table) = &self.loot_table else {
            return false;
        };
        nbt.insert("LootTable", loot_table.to_string());
        if self.seed != 0 {
            nbt.insert("LootTableSeed", self.seed);
        }
        true
    }

    /// Whether a loot table is still waiting to be rolled.
    #[must_use]
    pub const fn is_pending(&self) -> bool {
        self.loot_table.is_some()
    }

    /// Clears and returns the pending table, mirroring Vanilla's
    /// `setLootTable(null)` before the fill.
    ///
    /// Taking the table first lets the caller hand the same container to
    /// [`unpack_container_loot`] without aliasing the loot state.
    pub fn take(&mut self) -> Option<PendingContainerLoot> {
        let loot_table = self.loot_table.take()?;
        let seed = mem::take(&mut self.seed);
        Some(PendingContainerLoot { loot_table, seed })
    }

    /// Sets the loot table and seed, mirroring Vanilla's `setLootTable`.
    pub fn set(&mut self, loot_table: Identifier, seed: i64) {
        self.loot_table = Some(loot_table);
        self.seed = seed;
    }
}

/// A loot table taken out of a [`ContainerLoot`], ready to be rolled.
pub struct PendingContainerLoot {
    loot_table: Identifier,
    seed: i64,
}

/// Vanilla `RandomizableContainer.unpackLootTable`.
///
/// Rolls the pending table into `container` and clears it. Vanilla routes every
/// container accessor through this; Steel's [`Container`] methods are
/// storage-local and must not reach the registry, so callers invoke this at the
/// boundaries where the contents become observable: opening the menu and
/// reading the comparator output.
pub fn unpack_container_loot(
    pending: PendingContainerLoot,
    container: &mut dyn Container,
    pos: BlockPos,
    luck: f32,
) {
    let PendingContainerLoot { loot_table, seed } = pending;
    let Some(table) = REGISTRY.loot_tables.by_key(&loot_table) else {
        log::warn!("Container at {pos:?} references unknown loot table {loot_table}");
        return;
    };

    // Vanilla selects a `LegacyRandomSource` from the stored seed and otherwise
    // falls back to the level's random source.
    let mut rng = if seed == 0 {
        LegacyRandom::from_entropy()
    } else {
        LegacyRandom::from_seed(seed as u64)
    };
    let mut context = LootContext::new(&mut rng).with_luck(luck).with_origin(
        f64::from(pos.x()) + 0.5,
        f64::from(pos.y()) + 0.5,
        f64::from(pos.z()) + 0.5,
    );

    fill_container(table, container, &mut context);
}

#[cfg(test)]
mod tests {
    use steel_registry::vanilla_loot_tables::CHESTS_SIMPLE_DUNGEON;
    use steel_registry::{init_vanilla_registry, vanilla_items};
    use steel_utils::random::RandomSplitter;

    use super::*;
    use crate::inventory::container::SimpleContainer;

    struct CountingRandom {
        inner: LegacyRandom,
        draws: usize,
    }

    impl CountingRandom {
        fn new(seed: u64) -> Self {
            Self {
                inner: LegacyRandom::from_seed(seed),
                draws: 0,
            }
        }
    }

    impl Random for CountingRandom {
        fn fork(&mut self) -> Self {
            Self {
                inner: self.inner.fork(),
                draws: 0,
            }
        }

        fn next_i32(&mut self) -> i32 {
            self.draws += 1;
            self.inner.next_i32()
        }

        fn next_i32_bounded(&mut self, bound: i32) -> i32 {
            self.draws += 1;
            self.inner.next_i32_bounded(bound)
        }

        fn next_i64(&mut self) -> i64 {
            self.draws += 1;
            self.inner.next_i64()
        }

        fn next_f32(&mut self) -> f32 {
            self.draws += 1;
            self.inner.next_f32()
        }

        fn next_f64(&mut self) -> f64 {
            self.draws += 1;
            self.inner.next_f64()
        }

        fn next_bool(&mut self) -> bool {
            self.draws += 1;
            self.inner.next_bool()
        }

        fn next_gaussian(&mut self) -> f64 {
            self.draws += 1;
            self.inner.next_gaussian()
        }

        fn next_positional(&mut self) -> RandomSplitter {
            self.inner.next_positional()
        }
    }

    /// Vanilla `Mth.nextInt` returns `min` without drawing on a degenerate
    /// range. Drawing anyway would shift every later value in a seeded fill.
    #[test]
    fn degenerate_range_consumes_no_randomness() {
        let mut random = CountingRandom::new(42);
        assert_eq!(next_int_between(&mut random, 3, 3), 3);
        assert_eq!(next_int_between(&mut random, 5, 2), 5);
        assert_eq!(random.draws, 0);

        assert!((0..=1).contains(&next_int_between(&mut random, 0, 1)));
        assert_eq!(random.draws, 1);
    }

    /// A shuffle must consume one draw per swap, in descending index order, or
    /// a seeded chest lays its items out differently from Vanilla.
    #[test]
    fn shuffle_consumes_one_draw_per_element_above_the_first() {
        let mut random = CountingRandom::new(7);
        let mut values = [0, 1, 2, 3, 4];
        shuffle(&mut values, &mut random);

        assert_eq!(random.draws, 4);
        let mut sorted = values;
        sorted.sort_unstable();
        assert_eq!(sorted, [0, 1, 2, 3, 4]);
    }

    #[test]
    fn split_moves_stacks_out_of_the_result_until_slots_are_covered() {
        init_vanilla_registry();
        let mut random = LegacyRandom::from_seed(99);
        let mut result = vec![ItemStack::with_count(&vanilla_items::STONE, 64)];

        shuffle_and_split_items(&mut result, 8, &mut random);

        // Every produced stack is non-empty and the total count is preserved.
        assert!(result.len() > 1, "a 64-stack should split across 8 slots");
        assert!(result.iter().all(|item| item.count() > 0));
        assert_eq!(result.iter().map(ItemStack::count).sum::<i32>(), 64);
    }

    #[test]
    fn same_seed_fills_a_container_identically() {
        init_vanilla_registry();
        let table = &CHESTS_SIMPLE_DUNGEON;

        let fill_once = || {
            let mut container = SimpleContainer::new(27);
            let mut rng = LegacyRandom::from_seed(0xDEAD_BEEF);
            let mut context = LootContext::new(&mut rng).with_origin(0.5, 64.5, 0.5);
            fill_container(table, &mut container, &mut context);
            (0..container.get_container_size())
                .map(|slot| {
                    let item = container.get_item(slot);
                    (item.item().key.clone(), item.count())
                })
                .collect::<Vec<_>>()
        };

        let first = fill_once();
        assert_eq!(first, fill_once());
        assert!(
            first.iter().any(|(_, count)| *count > 0),
            "a dungeon chest fill should place at least one item"
        );
    }
}
