name: live_forever

on:
  push:
    branches:
      - master
    tags:
      - v**
  repository_dispatch:
    types:
      - steel-released
  workflow_dispatch:

permissions:
  contents: read

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha || github.sha }}
      - uses: sdruskat/swh-save-action@v1.0.1
